#ifndef LOCALIZATION_JP_H
#define LOCALIZATION_JP_H

#pragma once

#include <unordered_map>
#include <string>

inline std::unordered_map<std::string, std::string> getJapaneseTranslations() {
    return {
        // Auth Menu
        {"Login", "ログイン"},
        {"Password", "パスワード"},
        {"Auth", "認証"},
        {"Loading...", "読み込み中..."},
        {"Welcome back, ", "おかえりなさい "},
        {"Active subscriptions: ", "有効なサブスクリプション: "},
        {"Join cp.skateware.win for cloud radar, resources and more!", "cp.skateware.winに参加してクラウドレーダーや\nリソースなどを手に入れよう！"},
        {"Select cheat type below to load", "チートを選択して読み込む"},
        {"Cheat version: ", "チートバージョン: "},
        {" Server Version: ", " サーバーバージョン: "},
        {"Regular Cheat", "通常版"},
        {"Global DMA Cheat", "グローバルDMA版"},
        {"CN DMA Cheat", "中国DMA版"},

        {"Cant connect to server.", "サーバーに接続できません"},
        {"Invalid login or password.", "無効なログインまたはパスワード"},
        {"Invalid HWID.", "無効なHWID。"},
        {"Cant get cheat version.", "チートバージョンを取得できません"},
        {"Cheat was updated. Restart loader", "チートが更新されました。ローダーを再起動してください"},
        {"Failed to download file. Download it on the official website.", "ファイルのダウンロードに失敗しました。公式サイトからダウンロードしてください。"},
        {"The update has been successfully installed. Close this application, delete the old build and start the new one with the file name: ", "正常にアップデートされました。このアプリケーションを終了し、古いビルドを削除して、以下ファイル名の新しいビルドを実行してください: "},

        // Entity
        {"Chest", "宝箱"},
        {"Gallow", "ロケットチェア"},
        {"Cipher", "暗号機"},
        {"Pallet", "板"},
        {"Dungeon", "脱出口"},
        {"Cabinet", "ロッカー"},
        {"Crow", "カラス"},

        {"Lucky Guy", "幸運児"},
        {"Doctor", "医師"},
        {"Lawyer", "弁護士"},
        {"Thief", "泥棒"},
        {"Gardener", "庭師"},
        {"Magician", "マジシャン"},
        {"Explorer", "冒険家"},
        {"Mercenary", "傭兵"},
        {"Coordinator", "空軍"},
        {"Mechanic", "機械技師"},
        {"Robot", "ロボット"},
        {"Forward", "オフェンス"},
        {"The Minds Eye", "心眼"},
        {"Priestess", "祭司"},
        {"Perfumer", "調香師"},
        {"Cowboy", "カウボーイ"},
        {"Female Dancer", "踊り子"},
        {"Seer", "占い師"},
        {"Embalmer", "納棺師"},
        {"Prospector", "探鉱者"},
        {"Enchantress", "呪術師"},
        {"Wildling", "野人"},
        {"Acrobat", "曲芸師"},
        {"First Officer", "一等航海士"},
        {"Barmaid", "バーメイド"},
        {"Postman", "ポストマン"},
        {"Gravekeeper", "墓守"},
        {"Prisoner", "囚人"},
        {"Entomologist", "昆虫学者"},
        {"Painter", "画家"},
        {"Batter", "バッツマン"},
        {"Toy Merchant", "玩具職人"},
        {"Psychologist", "心理学者"},
        {"Patient", "患者"},
        {"Novelist", "小説家"},
        {"Little Girl", "少女"},
        {"Weeping Clown", "泣きピエロ"},
        {"Professor", "教授"},
        {"Antiquarian", "骨董商"},
        {"Composer", "作曲家"},
        {"Journalist", "記者"},
        {"Aeroplanist", "航空エンジニア"},
        {"Cheerleader", "応援団"},
        {"Puppeteer", "人形師"},
        {"Faro Lady", "レディファウロ"},
        {"Fire Investigator", "火災調査員"},

        {"Hell Ember", "レオ"},
        {"Smiley Face", "道化師"},
        {"Gamekeeper", "断罪狩人"},
        {"Ripper", "リッパー"},
        {"Soul Weaver", "結魂者"},
        {"Geisha", "芸者"},
        {"The Feaster", "黄衣の王"},
        {"Wu Chang", "白黒無常"},
        {"Black Wu Chang", "黒無常"},
        {"White Wu Chang", "白無常"},
        {"Photographer", "写真家"},
        {"Mad Eyes", "狂眼"},
        {"Dream Witch Follower", "信徒"},
        {"Dream Witch Main", "夢魔本体"},
        {"Axe Boy", "泣き虫"},
        {"Evil Reptilian", "魔トカゲ"},
        {"Bloody Queen", "血の女王"},
        {"Guard 26", "ガードNo26"},
        {"Disciple", "使徒"},
        {"Violinist", "ヴァイオリニスト"},
        {"Sculptor", "彫刻家"},
        {"Undead", "アンデッド"},
        {"Broken Wheel State", "破輪(車輪)"},
        {"Broken Wheel", "破輪"},
        {"Naiad", "漁師"},
        {"Wax Artist", "蠟人形師"},
        {"Nightmare", "悪夢"},
        {"Clerk", "書記官"},
        {"Electro Ball", "電磁ボール"},
        {"Hermit", "隠者"},
        {"Night Watch", "夜の番人"},
        {"Opera Singer", "オペラ歌手"},
        {"Opera Singer Shadow", "オペラ(潜行)"},
        {"Fool's Gold", "フルーズゴールド"},
        {"The Shadow", "時空の影"},
        {"The Yithian", "イース人"},

        {"Syringe", "注射器"},
        {"Map", "地図"},
        {"Flashlight", "懐中電灯"},
        {"Toolbox", "工具箱"},
        {"Decoy", "ステッキ"},
        {"Explorer's Book", "冒険家の本"},
        {"Iron Dash", "肘あて"},
        {"Flaregun", "信号銃"},
        {"Controller", "リモコン"},
        {"Football", "ラグビーボール"},
        {"Perfume", "香水"},
        {"Lasso", "縄"},
        {"Magnet", "磁石"},
        {"Fast Music Box", "青オルゴール"},
        {"Slow Music Box", "赤オルゴール"},
        {"Fire Bomb", "燃焼爆弾"},
        {"Sticky Bomb", "粘着爆弾"},
        {"Nitro Bomb", "冷却爆弾"},
        {"Watch", "懐中時計"},
        {"Dovlin", "ドーフリン酒"},
        {"Shovel", "スコップ"},
        {"Net", "虫取り網"},
        {"Grappling Hooks", "鉤爪"},
        {"Rocket", "ロケット"},
        {"Mechanical Flute", "仕掛け簫"},
        {"Crowbar", "バール"},
        {"Smoke Bottle", "煙幕瓶"},
        {"Black Mud", "黒いヘドロ"},
        {"Coldsnap Flask", "冷凍瓶"},
        {"Telephone", "電話ボックス"},

        {"Coffin", "棺桶"},
        {"Mail Dog", "配達犬"},
        {"Painting", "キャンバス"},
        {"Catapult", "弾射板車"},
        {"Cricket Ball", "クリケットボール"},
        {"Memory Fragment", "記憶の断片(少女)"},
        {"Flashlight", "懐中電灯"},
        {"Boar", "イノシシ"},
        {"Swarm of Bees", "虫の群れ"},
        {"Professor's Scale", "教授の鱗"},
        {"Orpheus", "幻影"},
        {"Inflatable Airbag", "エアーボール"},

        {"Patroller", "巡視者"},
        {"Peeper", "監視者"},
        {"Golem", "黒レオ"},
        {"Doll", "黄パペット"},
        {"Red Doll", "赤パペット"},
        {"Trap", "トラバサミ"},
        {"Butterfly", "蝶"},
        {"Tentacle", "触手"},
        {"Peaceful Pine", "安息松"},
        {"Branch", "枝"},
        {"Mirror", "鏡"},
        {"Bomb", "時限爆弾"},
        {"Exploding Bomb", "起爆した爆弾"},
        {"Cat Hint", "猫のガイド"},
        {"Cat", "猫"},
        {"Knife", "彫刻刀"},
        {"Pickaxe", "つるはし"},
        {"Magnetic Rock", "引力の石"},
        {"Corrupted Ostracon", "侵蝕の断片"},

        // feature
        {"Fire attack triggered on ", "攻撃発動: "},
        {"Auto statue triggered on ", "自動彫刻像が発動: "},
        {"Predicted Note", "予測点"},
        {"Survivor on diagonal, auto-violinist triggered on ", "サバイバーが対角線上にいたため自動弦が発動: "},
        {"Emergency shutdown of pallet dropping, possibly baited by hunter", "ハンターがフェイントをしている可能性があるため、自動板倒しが無効になりました。"},
        {"Forcibly dump the pallet, the hunter is standing in place in it", "自動板倒しによってハンターがスタンしました"},
        {"Dropped pallet on ", "板を倒した: "},
        {" | Conditions: In Bounds(", " | 状況: 範囲内("},
        {") Predicted(", ") 予測("},
        {") Antibaited(", ") フェイント対策("},
        {"Umbrella mark is under survivor, teleporting...", "傘マークがサバイバーの近くにあるため、テレポート中..."},
        {"Waiting for the opponent to choose...", "相手が選択するのを待っています..."},
        {"The opponent chose: ", "ハンターのキャラ選択: "},
        {"The first opponent chose: ", "1番目のハンターのキャラ選択: "},
        {"Hunter Indicator", "ハンター表示"},
        {"%s [Cooldown: %d sec]", "%s [クールタイム: %d 秒]"},
        {"%s [Ready]", "%s [準備完了]"},
        {"Listen", "リッスン"},
        {"Abnormal", "異常"},
        {"Excitement", "興奮"},
        {"Patroller", "巡視者"},
        {"Peeper", "監視者"},
        {"Blink", "神出鬼没"},
        {"Warp", "移形"},
        {"Flywheel", "フライホイール効果"},
        {"Tide Turner", "仲直り"},
        {"Borrowed Time", "危機一髪"},
        {"Window Boost", "膝蓋腱反射"},
        {"Confined Space", "閉鎖空間"},
        {"Trump Card", "裏向きカード"},
        {"Detention", "引き留める"},
        {"Insolence", "傲慢"},
        {" (Bot)", " (ボット)"},
        {", Skill: ", ", スキル: "},
        {", Talents: ", ", 人格: "},
        {"Bot", "ボット"},
        {"[ Destroyed ]", "[ 破壊済み ]"},
        {"[ Unused ]", "[ 未使用 ]"},
        {"[ Used ]", "[ 使用済み ]"},

        // Messages
        {"Don't forget to join our discord server, all the news, developer videos and chats are posted there!",
            "Discordサーバーに参加するのを忘れないでください。すべてのお知らせや、開発者の動画、チャットがそこにあります！"},
        {"Our team is constantly working to improve Skateware and add new features. Stay tuned for updates!",
            "私たちはSkatewareを常に改善し、機能追加を行っています。更なるアップデートをお楽しみに！"},
        {"Thanks for using Skateware! Your support and feedback are greatly appreciated.",
            "Skatewareをご利用いただきありがとうございます。皆様の支援とフィードバックに感謝しています。"},
        {"Are you a streamer or content creator? Ask about our affiliate program and earn rewards for promoting Skateware.",
            "あなたは配信者？それとも動画クリエイターですか？Skatewareを宣伝してアフィリエイト報酬を受け取ろう！"},
        {"Have a suggestion for a new feature? We'd love to hear it! Head to our forums to share your ideas.",
            "新機能の案がありますか？ぜひお聞かせください！フォーラムにアクセスしてアイデアを共有しよう。"},
        {"We appreciate your feedback! Let us know what you think of Skateware so far.",
            "フィードバックに感謝します！これまでのSkatewareに対するご意見をお聞かせください。"},
        {"Want to stay up-to-date on Skateware news and updates? Follow us on social media!",
            "Skatewareのお知らせやアップデート情報を受け取りたいですか？私たちのSNSをフォローしてください！"},
        {"Don't forget to check out our FAQ section for answers to common questions.",
            "FAQ項目によくある質問への回答があることをお忘れなく！"},
        {"Skateware Lua API is designed to be easy to use, even if you're new to game development. Give it a try!",
            "Skateware Lua APIは使いやすいよう設計されています。ゲーム開発が不慣れな方でも簡単にできるので、ぜひお試しください！"},
        {"Did you know that Skateware has a Lua API? With Lua scripting, you can customize your game and add new features with ease.",
            "SkatewareにはLua APIがあるのをご存知ですか？Luaスクリプトを使うことで、簡単にカスタマイズし、あなただけの機能を追加できます。"},
        {"Calling all developers! Our Lua API makes it easy to create custom gameplay mechanics and more. Give it a try!",
            "すべての開発者にお知らせです！私たちのLua APIを使えば、自由なゲームプレイを実現できるため、ぜひお試しください！"},
        {"Looking to take your game to the next level? Our Lua API lets you create custom tools and workflows for Skateware.",
            "あなたのゲーム体験を次のレベルへ引き上げたいですか？私たちのLua APIを使えば、Skateware向けのカスタムツールやマクロを作成できます。"},
        {"With the power of Lua scripting, the possibilities for cheat development with Skateware are endless. Join our community and start creating!",
            "Luaスクリプトの力を使えば、Skatewareでのチート開発の可能性は無限大です。コミュニティに参加して、創作を始めましょう！"},
        {"Are you a Lua expert? We'd love to see what you can create with Skateware's Lua API. Join our community and share your projects!",
            "あなたはLuaの熟練者ですか？SkatewareのLua APIで何を作りましょう。コミュニティに参加して、あなたのプロジェクトを共有してください！"},
        {"Whether you're a seasoned developer or just getting started, Skateware's Lua API is a powerful tool for creating amazing games. Join our community and start coding today!",
            "経験豊富な開発者でも、これから始める方でも、SkatewareのLua APIは素晴らしいゲームを作るための強力なツールです。コミュニティに参加して、今すぐLuaを始めましょう！"},

        {"Reconnected!", "再接続しました！"},
        {"Can't connect to server...", "サーバーに接続できません..."},
        {"Can't connect to server, trying again...", "サーバーに接続できません、再試行しています..."},
        {"Failed to find Identity V process. Try to restart loader", "Identity Vのプロセスが見つかりませんでした。ローダーを再起動してください"},
        {"Failed to find process. Start Identity V first!", "プロセスが見つかりません。まずIdentity Vを起動してください！"},
        {"You dont have access to Chinese version of the hack.", "中国語版のチートにアクセスできません"},
        {"You can open the menu with the \"F11\" button", "\"F11\"キーでメニューを開くことができます"},
        {"Fonts was rebuilded", "フォントが再構築されました"},
        {"Cannot find target window!", "ターゲットウィンドウが見つかりません！"},
        {"Skinchanger: Skin was applied.", "衣装変更: 衣装が適用されました"},
        {"Skinchanger: Skins were restored.", "衣装変更: 元の衣装に戻りました"}
        
        // Menu
        {"Premium Identity V Cheat", "最高級の第五人格チート"},
        {"Navigation", "ナビゲーション"},
        {"Rage", "対戦"},
        {"RAGE", "対戦"},
        {"Visuals", "描画"},
        {"VISUALS", "描画"},
        {"Misc", "その他"},
        {"Miscellaneous", "その他"},
        {"MISC", "その他"},
        {"Lua", "Lua"},
        {"Skin Changer", "衣装変更"},
        {"Click to open live match radar", "ここをクリックしてウェブレーダーを開く"},
        {"Are you sure you want to exit the cheat?", "チートを終了してもよろしいですか?"},
        {"Exit", "終了"},
        {"No", "いいえ"},
        {"MAIN", "メイン"},
        {"SURVIVOR", "サバイバー"},
        {"HUNTER", "ハンター"},
        {"WORLD", "ワールド"},
        {"Lua scripts", "Lua スクリプト"},
        {"Lua # ", "Lua # "},
        {"Everyone", "全員"},
        {"Suvivor", "サバイバーのみ"},
        {"Hunter", "ハンターのみ"},
        
        {"Lock", "固定"},
        {"Aimbot", "エイムボット"},
        {"Help with cursor fine-tuning", "カーソル移動の補助"},
        {"Auto Fire", "自動攻撃"},
        {"Predict", "予測"},
        {"FOV Radius", "FOV範囲"},
        {"Target", "対象"},
        {"Mode", "モード"},
        {"Distance Mode", "距離モード"},
        {"Field Of View", "視野角"},
        {"Sensitivity", "感度"},
        {"Smooth", "スムーズ"},
        {"Predict Offset", "予測のオフセット"},
        {"Prediction offset", "予測のオフセット"},
        {"Lag Switch", "ラグ切り替え"},
        {"Block", "ブロック"},
        {"Incoming", "受信"},
        {"Outgoing", "送信"},
        {"All", "すべて"},
        {"Beep Sound", "ビープ音"},
        {"Auto pallet drop", "自動板倒し"},
        {"Rapid drop", "即板倒し"},
        {"Rapid mode", "高速モード"},
        {"Legit", "安全"},
        {"Blatant", "露骨"},
        {"Ignore status", "状態無視"},
        {"Activation key", "発動キー"},
        {"Drop distance", "倒す距離"},
        {"Direction offset", "方向のオフセット"},
        {"Remove baited check", "フェイント検出無効化"},
        {"Auto skill", "自動スキル"},
        {"Distance", "距離"},
        {"Cooldown", "クールタイム"},
        {"Detail setup", "詳細設定"},
        {"Second press", "二回押し"},
        {"Second press delay", "二回押しの間隔"},
        {"When facing angle", "後ろ向き時のみ"},
        {"Angle value", "角度値"},
        {"Hunter automations", "ハンター自動化"},
        {"Select Hunter", "ハンター選択"},
        {"Evil Reptilian", "魔トカゲ"},
        {"Guard 26", "ガードNo26"},
        {"Violinis", "バイオリニスト"},
        {"Axe Boy", "泣き虫"},
        {"Wu Chang", "白黒無常"},
        {"Auto lizard jump", "自動ジャンプ"},
        {"Radius", "半径"},
        {"Predict position", "位置予測"},
        {"Auto bomb", "自動爆弾"},
        {"Drop offset", "設置のオフセット"},
        {"Aim at second", "2秒で狙う"},
        {"Auto violinist", "自動弦"},
        {"Threshold", "範囲値"},
        {"Auto Robbie", "自動泣き虫"},
        {"Hit Threshold", "発動範囲値"},
        {"Umbrella helper", "傘ワープ補助"},
        {"Teleport on distance", "距離に応じてワープ"},
        {"Draw ESP", "ESPを描画"},
        {"DMA Background", "DMAバックグラウンド"},
        {"Entities Panel", "エンティティパネル"},
        {"Show only players", "プレイヤーのみ表示"},
        {"Panel Corner", "パネル位置"},
        {"Top Left", "左上"},
        {"Bottom Left", "左下"},
        {"Top Right", "右上"},
        {"Bottom Right", "右下"},
        {"Middle Left", "左中"},
        {"Middle Right", "右中"},
        {"Old FOV Method", "旧視野角変更方法"},
        {"FOV Value", "視野角値"},
        {"No Fog", "霧消し"},
        {"Fog Value", "霧の値"},
        {"Widescreen 4:3", "ワイドスクリーン4:3"},
        {"Offscreen ESP", "画面外ESP"},
        {"Offset", "オフセット"},
        {"Triangle Size", "矢印の大きさ"},
        {"Survivor", "サバイバー"},
        {"Draw survivor", "サバイバー描画"},
        {"Draw boxes", "ボックス描画"},
        {"BOX TYPE", "ボックス種類"},
        {"Standart", "標準"},
        {"Corner box", "四角ボックス"},
        {"Circle", "円形"},
        {"Draw snap line", "ラインを描画"},
        {"SNAP LINE TYPE", "ラインの位置"},
        {"Upper", "上部"},
        {"Center", "中央"},
        {"Bottom", "下部"},
        {"Max render distance", "最大描画距離"},
        {"Draw distance", "描画距離"},
        {"Draw objects", "設置物を描画"},
        {"Draw mirrored", "鏡を描画"},
        {"Lizard Helper", "魔トカゲ補助"},
        {"Items", "アイテム"},
        {"Draw items", "アイテムを描画"},
        {"ITEM BOX TYPE", "ボックスの位置"},
        {"Hunter", "ハンター"},
        {"Draw hunter", "ハンターを描画"},
        {"Peeper ESP", "監視者ESP"},
        {"Show while waiting", "待機中も表示"},
        {"Show skill indicator", "スキルCT表示"},
        {"Pallets", "板"},
        {"Draw pallets", "板を描画"},
        {"Draw status", "状態を描画"},
        {"Ciphers", "暗号機"},
        {"Draw ciphers", "暗号機を描画"},
        {"Show progress", "暗号気進捗を表示"},
        {"Cabinets", "ロッカー"},
        {"Draw cabinets", "ロッカーを描画"},
        {"Gallows", "チェア"},
        {"Draw gallows", "チェアを描画"},
        {"Dungeon", "脱出口"},
        {"Draw dungeon", "脱出口を描画"},
        {"Draw chests", "宝箱を描画"},
        {"Chests", "宝箱"}

        {"THEME", "テーマ"},
        {"Blue", "ブルー"},
        {"Purple", "パープル"},
        {"Custom", "カスタム"},
        {"CUSTOM", "カスタム"},
        {"Custom colors", "色変更"},
        {"Color 1", "色１"},
        {"Color 2", "色２"},
        {"Transparency", "透明度"},
        {"Refresh", "更新"},
        {"Folder", "フォルダー"},
        {"Save colors to theme", "テーマに色を保存"},
        {"Setup", "適応"},
        {"Protect Screen", "画面保護"},
        {"Safe Mode", "安全モード"},
        {"Watermark", "透かし文字"},
        {"Active Binds", "キー割り当て"},
        {"Menu Open Key", "メニュー表示キー"},
        {"Discord RPC", "Discord RPC"},
        {"Skateware Watermark", "Skateware透かし"},
        {"Skateware Chat", "Skatewareチャット"},
        {"Chat Transparency", "チャットの透明度"},
        {"DPI SCALE", "DPIスケール"},
        {"CONFIG", "設定"},
        {"Alpha", "アルファ"},
        {"Beta", "ベータ"},
        {"Gamma", "ガンマ"},
        {"Delta", "デルタ"},
        {"Zeta", "ゼータ"},
        {"Load", "読み込む"},
        {"Save", "保存"},
        {"Open Folder", "フォルダーを開く"},
        {"Python", "Python"},
        {"Extend functionality now!", "今すぐ機能を拡張しよう!"},
        {"Enable", "有効化"},
        {"Show nicknames", "ニックネーム表示"},
        {"Show skill", "スキル表示"},
        {"Show talents", "人格表示"},
        {"Show bots", "ボット表示"},
        {"Python not initialised", "Pythonが初期化されていません"},
        {"Install Python", "Pythonをインストール"},

        {"SKIN CHANGER", "衣装変更"},
        {"PREVIEW ACCESS", "試用版"},
        {"Apply Skin", "衣装適用"},
        {"Restore Default", "元に戻す"},
        {"You don't have access to Skin Changer!", "衣装変更を利用する権限がありません！"},
        {"Select any skin", "任意の衣装選択"},
        {"CHARACTER", "キャラクター"},
        {"SKIN NAME", "衣装名"},
        {"Skin Preview", "衣装プレビュー"},
        {"To use Skin Changer, you need to purchase a subscription \nto the cheat supplement on the skateware.win website.", "衣装変更を使用するにはサブスクリプションを行う必要があります\n詳しくはskateware.winのウェブサイトを確認してください"},
        {"Your task is to first select the Default skin of the desired character, \nthen select the desired skin in the Skin Changer settings and click Apply. \nYou don't need to do anything else with skins. \nIt is also forbidden to change the skin until the skinchanger restores the skins. \nOtherwise, you will not be allowed into the match.", "任意キャラの初期衣装を選択してから、\n衣装変更の設定から任意衣装を選択、適応をクリックしてください\nこれ以外は特になにかする必要はありません。\nまた、衣装変更を適応後、元に戻すまではゲーム内機能で衣装を変更しないでください\nこれを破ると試合に参加できなくな"},

        {"None", "未設定"},
        {"Input the letter", "キー入力"},
        {"Always on", "常時有効"},
        {"Hold", "長押し"},
        {"Toggle", "切り替え"},
        {"Force off", "強制無効化"},
        {"Configurate", "設定"},

        {"Version: ", "バージョン: "},
        {"Author: ", "作者: "},
        {"Stop##", "停止##"},
        {"Load##", "読み込み##"},
        {"Create", "作成"},
        {"File Name w/o .lua", "拡張子.luaなしのファイル名"},
        {"Open skateware folder", "Skatewareフォルダーを開く"},
        {"Open resources marketplace", "リソースマーケットプレイスを開く"},
        {"Open docs", "ドキュメントを開く"},
        {"Refresh cloud scripts", "クラウドスクリプトを更新"},

        {"ESP: ", "ESP: "},
        {"Auto pallet: ", "自動板倒し: "},
        {"Field Of View: ", "視野角: "},
        {"Lizard jump: ", "魔トカゲジャンプ: "},
        {"Lizard Helper: ", "魔トカゲ補助: "},
        {"Aimbot: ", "エイムボット: "},
        {"Auto skill: ", "自動スキル: "},
        {"Wu Chang Helper: ", "無常ワープ補助: "},
        {"Lag Switch: ", "ラグ切り替え: "},

        //added by fred0211
        {"The second opponent chose: ", "2番目のハンターのキャラ選択: " },
        {"Always On", "常時有効" },
        {"Teleport", "瞬間移動"},
        {"Statue", "石像"},
        {"Camera", "カメラ"},
        {"Lawer", "弁護士"},
        {"Harpoon", "銛"},
        {"Remnant", "残影"},
        {"Nightmare's crow", "渡鴉"},
    };
}

#endif // LOCALIZATION_JP_H
