#ifndef LOCALIZATION_RU_H
#define LOCALIZATION_RU_H

#pragma once

#include <unordered_map>
#include <string>

inline std::unordered_map<std::string, std::string> getRussianTranslations() {
    return {
        // Auth Menu
        {"Login", "Логин"},
        {"Password", "Пароль"},
        {"Auth", "Войти"},
        {"Loading...", "Загрузка..."},
        {"Welcome back, ", "Добро пожаловать, "},
        {"Active subscriptions: ", "Активные подписки: "},
        {"Join cp.skateware.win for cloud radar, resources and more!", "Заходи на cp.skateware.win для новых функций: веб-радар, скрипты и др.!"},
        {"Select cheat type below to load", "Выберите тип чита снизу для запуска"},
        {"Cheat version: ", "Версия чита: "},
        {" Server Version: ", " Версия сервера: "},
        {"Regular Cheat", "Обычный Чит"},
        {"Global DMA Cheat", "Global DMA Чит"},
        {"CN DMA Cheat", "CN DMA Чит"},

        {"Cant connect to server.", "Не удается подключиться к серверу."},
        {"Invalid login or password.", "Неверный логин или пароль."},
        {"Invalid HWID.", "Неверный HWID."},
        {"Cant get cheat version.", "Не удается получить версию чита."},
        {"Cheat was updated. Restart loader", "Чит был обновлен. Перезапустите лоадер."},
        {"Failed to download file. Download it on the official website.", "Не удалось загрузить файл. Загрузите лоадер на официальном сайте."},
        {"The update has been successfully installed. Close this application, delete the old build and start the new one with the file name: ", "Обновление успешно установлено. Закройте это приложение, удалите старый файл и запустите новый с именем: "},

        // Entity
        {"Chest", "Сундук"},
        {"Gallow", "Стул"},
        {"Cipher", "Генератор"},
        {"Pallet", "Паллета"},
        {"Dungeon", "Люк"},
        {"Cabinet", "Шкаф"},
        {"Crow", "Ворона"},

        {"Lucky Guy", "Счастливчик"},
        {"Doctor", "Доктор"},
        {"Lawyer", "Адвокат"},
        {"Thief", "Вор"},
        {"Gardener", "Садовница"},
        {"Magician", "Фокусник"},
        {"Explorer", "Исследователь"},
        {"Mercenary", "Наемник"},
        {"Coordinator", "Координатор"},
        {"Mechanic", "Механик"},
        {"Robot", "Робот"},
        {"Forward", "Нападающий"},
        {"The Minds Eye", "Экстрасенс"},
        {"Priestess", "Жрица"},
        {"Perfumer", "Парфюмер"},
        {"Cowboy", "Ковбой"},
        {"Female Dancer", "Танцовщица"},
        {"Seer", "Пророк"},
        {"Embalmer", "Бальзамировщик"},
        {"Prospector", "Геолог"},
        {"Enchantress", "Чаровница"},
        {"Wildling", "Дикарь"},
        {"Acrobat", "Акробат"},
        {"First Officer", "Первый Офицер"},
        {"Barmaid", "Барменша"},
        {"Postman", "Почтальон"},
        {"Gravekeeper", "Могильщик"},
        {"Prisoner", "Заключенный"},
        {"Entomologist", "Энтомолог"},
        {"Painter", "Художник"},
        {"Batter", "Баттер"},
        {"Toy Merchant", "Торговец игрушками"},
        {"Psychologist", "Психолог"},
        {"Patient", "Пациент"},
        {"Novelist", "Новеллист"},
        {"Little Girl", "Маленькая девочка"},
        {"Weeping Clown", "Плачущий клоун"},
        {"Professor", "Профессор"},
        {"Antiquarian", "Антиквар"},
        {"Composer", "Композитор"},
        {"Journalist", "Журналист"},
        {"Aeroplanist", "Летчик"},
        {"Cheerleader", "Чирлидер"},
        {"Puppeteer", "Кукольник"},
        {"Faro Lady", "Леди Фаро"},
        {"Fire Investigator", "Следователь по пожарам"},

        {"Hell Ember", "Адский пламень"},
        {"Smiley Face", "Улыбающееся лицо"},
        {"Gamekeeper", "Егерь"},
        {"Ripper", "Потрошитель"},
        {"Soul Weaver", "Ткач души"},
        {"Geisha", "Гейша"},
        {"The Feaster", "Пирующий"},
        {"Wu Chang", "Ву Чанг"},
        {"Black Wu Chang", "Черный Ву Чанг"},
        {"White Wu Chang", "Белый Ву Чанг"},
        {"Photographer", "Фотограф"},
        {"Mad Eyes", "Архитектор"},
        {"Dream Witch Follower", "Последователь ведьмы"},
        {"Dream Witch Main", "Главная ведьма"},
        {"Axe Boy", "Мальчик с топором"},
        {"Evil Reptilian", "Злая рептилия"},
        {"Bloody Queen", "Кровавая королева"},
        {"Guard 26", "Страж 26"},
        {"Disciple", "Апостол"},
        {"Violinist", "Скрипач"},
        {"Sculptor", "Скульптор"},
        {"Undead", "Нежить"},
        {"Broken Wheel State", "Состояние сломанного колеса"},
        {"Broken Wheel", "Сломанное колесо"},
        {"Naiad", "Наяда"},
        {"Wax Artist", "Восковой художник"},
        {"Nightmare", "Кошмар"},
        {"Clerk", "Математичка"},
        {"Electro Ball", "Электрошар"},
        {"Hermit", "Отшельник"},
        {"Night Watch", "Ночной наблюдатель"},
        {"Opera Singer", "Оперная певица"},
        {"Opera Singer Shadow", "Тень оперной певицы"},
        {"Fool's Gold", "Дурацкое золото"},
        {"The Shadow", "Тень"},
        {"The Yithian", "Иитиан"},

        { "Syringe", "Шприц" },
        { "Map", "Карта" },
        { "Flashlight", "Фонарик" },
        { "Toolbox", "Ящик с инструментами" },
        { "Decoy", "Приманка" },
        { "Explorer's Book", "Книга исследователя" },
        { "Iron Dash", "Наручи" },
        { "Flaregun", "Пистолет" },
        { "Controller", "Контроллер" },
        { "Football", "Футбольный мяч" },
        { "Perfume", "Духи" },
        { "Lasso", "Лассо" },
        { "Magnet", "Магнит" },
        { "Fast Music Box", "Быстрая музыкальная шкатулка" },
        { "Slow Music Box", "Медленная музыкальная шкатулка" },
        { "Fire Bomb", "Огненная бомба" },
        { "Sticky Bomb", "Липкая бомба" },
        { "Nitro Bomb", "Нитро бомба" },
        { "Watch", "Часы" },
        { "Dovlin", "Алкашка" },
        { "Shovel", "Лопата" },
        { "Net", "Сеть" },
        { "Grappling Hooks", "Кошки" },
        { "Rocket", "Ракета" },
        { "Mechanical Flute", "Механическая флейта" },
        { "Crowbar", "Лом" },
        { "Smoke Bottle", "Дымовая бутылка" },
        { "Black Mud", "Бутылка с грязью" },
        { "Coldsnap Flask", "Колба с холодом" },
        { "Telephone", "Телефон" },

        { "Coffin", "Гроб" },
        { "Mail Dog", "Почтовая собака" },
        { "Painting", "Картина" },
        { "Catapult", "Катапульта" },
        { "Cricket Ball", "Крикетный мяч" },
        { "Memory Fragment", "Фрагмент памяти" },
        { "Flashlight", "Фонарик" },
        { "Boar", "Кабан" },
        { "Swarm of Bees", "Рой пчел" },
        { "Professor's Scale", "Щит профессора" },
        { "Orpheus", "Орфей" },
        { "Inflatable Airbag", "Надувная подушка безопасности" },

        { "Patroller", "Патрульный" },
        { "Peeper", "Смотритель" },
        { "Golem", "Голем" },
        { "Doll", "Кукла" },
        { "Red Doll", "Красная кукла" },
        { "Trap", "Ловушка" },
        { "Butterfly", "Бабочка" },
        { "Tentacle", "Щупальце" },
        { "Peaceful Pine", "Мирная сосна" },
        { "Branch", "Ветка" },
        { "Mirror", "Зеркало" },
        { "Bomb", "Бомба" },
        { "Exploding Bomb", "Взрывающаяся бомба" },
        { "Cat Hint", "Подсказка кота" },
        { "Cat", "Кот" },
        { "Statue", "Статуя" },
        { "Knife", "Нож" },
        { "Harpoon", "Гарпун" },
        { "Nightmare's Crow", "Ворон кошмара" },
        { "Remnant", "Остаток" },
        { "Shadow Cloak", "Плащ тени" },
        { "Wall", "Стена" },
        { "Camera", "Камера" },
        { "Console", "Консоль" },
        { "Pickaxe", "Кирка" },
        { "Magnetic Rock", "Магнитная скала" },
        { "Corrupted Ostracon", "Оскверненный остракон" },

        // features
        { "Fire attack triggered on ", "Атака духом проведена по " },
        { "Auto statue triggered on ", "Атака статуей проведена по " },
        { "Predicted Note", "Предсказанная нота" },
        { "Survivor on diagonal, auto-violinist triggered on ", "Выживший по диагонали, авто-скрипач активирован по " },
        { "Emergency shutdown of pallet dropping, possibly baited by hunter", "Аварийное отключение авто-паллеты, возможно, провоцирование охотником" },
        { "Forcibly dump the pallet, the hunter is standing in place in it", "Аварийное скидывание авто-паллеты, охотник стоит в паллете на месте" },
        { "Dropped pallet on ", "Паллета скинута на " },
        { " | Conditions: In Bounds(", " | Условия: В Границах(" },
        { ") Predicted(", ") Предсказано("},
        { ") Antibaited(", ") Не Спровоцировано("},
        { "Umbrella mark is under survivor, teleporting...", "Метка зонтика на выжившем, телепортируемся..." },
        { "Waiting for the opponent to choose...", "Ожидаем выбор оппонента..." },
        { "The opponent chose: ", "Выбор оппонента: " },
        { "The first opponent chose: ", "Выбор первого оппонента: " },
        { "The second opponent chose: ", "Выбор второго оппонента: " },
        { "Hunter Indicator", "Индикаторы Охотника" },
        { "%s [Cooldown: %d sec]", "%s [Перезарядка: %d сек]" },
        { "%s [Ready]", "%s [Готово]" },
        { "Listen", "Прослушивание" },
        { "Abnormal", "Разрушение генератора" },
        { "Excitement", "Антистан" },
        { "Patroller", "Патрульный" },
        { "Teleport", "Телепорт" },
        { "Peeper", "Подглядывающий" },
        { "Blink", "Скачок (блинк)" },
        { "Warp", "Перемещение" },
        { "Flywheel", "Орех" },
        { "Tide Turner", "Часы" },
        { "Borrowed Time", "Отложенное время" },
        { "Window Boost", "Бусты от окон" },
        { "Confined Space", "Закрывашка" },
        { "Trump Card", "Смена способности" },
        { "Detention", "Красные глаза, хуй знает" },
        { "Insolence", "Накопление первого навыка" },
        { " (Bot)", " (Бот)" },
        { ", Skill: ", ", Навык: " },
        { ", Talents: ", ", Таланты: " },
        { "Bot", "Бот" },
        { "[ Destroyed ]", "[ Разрушено ]" },
        { "[ Unused ]", "[ Не использовано ]" },
        { "[ Used ]", "[ Использовано ]" },

        // Messages
        { "Don't forget to join our discord server, all the news, developer videos and chats are posted there!",
            "Не забудьте присоединиться к нашему серверу в Discord, все новости, видео разработчиков и чаты размещены там!" },
        { "Our team is constantly working to improve Skateware and add new features. Stay tuned for updates!",
            "Наша команда постоянно работает над улучшением Skateware и добавлением новых функций. Оставайтесь с нами для получения обновлений!" },
        { "Thanks for using Skateware! Your support and feedback are greatly appreciated.",
            "Спасибо за использование Skateware! Ваша поддержка и отзывы очень ценны." },
        { "Are you a streamer or content creator? Ask about our affiliate program and earn rewards for promoting Skateware.",
            "Вы стример или создатель контента? Узнайте о нашей партнерской программе и получайте награды за продвижение Skateware." },
        { "Have a suggestion for a new feature? We'd love to hear it! Head to our forums to share your ideas.",
            "Есть предложение по новой функции? Мы будем рады его услышать! Переходите на наш форум, чтобы поделиться своими идеями." },
        { "We appreciate your feedback! Let us know what you think of Skateware so far.",
            "Мы ценим ваши отзывы! Сообщите нам, что вы думаете о Skateware на данный момент." },
        { "Want to stay up-to-date on Skateware news and updates? Follow us on social media!",
            "Хотите быть в курсе новостей и обновлений Skateware? Подписывайтесь на нас в социальных сетях!" },
        { "Don't forget to check out our FAQ section for answers to common questions.",
            "Не забудьте проверить наш раздел с часто задаваемыми вопросами для получения ответов на распространенные вопросы." },
        { "Skateware Lua API is designed to be easy to use, even if you're new to game development. Give it a try!",
            "API Lua от Skateware разработан таким образом, чтобы его было легко использовать, даже если вы новичок в разработке игр. Попробуйте!" },
        { "Did you know that Skateware has a Lua API? With Lua scripting, you can customize your game and add new features with ease.",
            "Знаете ли вы, что у Skateware есть API Lua? С помощью скриптов на Lua вы можете настраивать свою игру и добавлять новые функции с легкостью." },
        { "Calling all developers! Our Lua API makes it easy to create custom gameplay mechanics and more. Give it a try!",
            "Призываем всех разработчиков! Наш API Lua позволяет легко создавать собственные игровые механики и многое другое. Попробуйте!" },
        { "Looking to take your game to the next level? Our Lua API lets you create custom tools and workflows for Skateware.",
            "Хотите вывести свою игру на новый уровень? Наш API Lua позволяет создавать собственные инструменты и рабочие процессы для Skateware." },
        { "With the power of Lua scripting, the possibilities for cheat development with Skateware are endless. Join our community and start creating!",
            "С мощью скриптов на Lua возможности для разработки читов с Skateware безграничны. Присоединяйтесь к нашему сообществу и начинайте создавать!" },
        { "Are you a Lua expert? We'd love to see what you can create with Skateware's Lua API. Join our community and share your projects!",
            "Вы эксперт по Lua? Мы будем рады увидеть, что вы можете создать с помощью API Lua от Skateware. Присоединяйтесь к нашему сообществу и делитесь своими проектами!" },
        { "Whether you're a seasoned developer or just getting started, Skateware's Lua API is a powerful tool for creating amazing games. Join our community and start coding today!",
            "Будь вы опытным разработчиком или только начинающим, API Lua от Skateware - это мощный инструмент для создания удивительных игр. Присоединяйтесь к нашему сообществу и начните кодить уже сегодня!" },

        { "Reconnected!", "Переподключено!" },
        { "Can't connect to server...", "Не получается подключиться к серверу..." },
        { "Can't connect to server, trying again...", "Не получается подключиться к серверу, пробуем еще раз..." },
        { "Failed to find Identity V process. Try to restart loader", "Не удается найти процесс Identity V. Попробуйте перезапустить лоадер" },
        { "Failed to find process. Start Identity V first!", "Не удается найти процесс Identity V. Запустите игру в первую очередь!" },
        { "You dont have access to Chinese version of the hack.", "У вас нет доступа к китайской версии чита." },
        { "You can open the menu with the \"F11\" button", "Вы можете открыть меню чита с помощью кнопки \"F11\"." },
        { "Fonts was rebuilded", "Шрифты были перезагружены" },
        { "Cannot find target window!", "Не удается найти процесс Identity V" },
        { "Skinchanger: Skin was applied.", "Скинченджер: Скин был применен." },
        { "Skinchanger: Skins were restored.", "Скинченджер: Скины были восстановлены." },

        // Menu
        { "Premium Identity V Cheat", "Премиум Identity V Чит" },
        { "Navigation", "Навигация" },
        { "Rage", "Рейдж" },
        { "RAGE", "RAGE" },
        { "Visuals", "Визуал" },
        { "VISUALS", "VISUALS" },
        { "Misc", "Дополнительное" },
        { "MISC", "ДОПОЛНИТЕЛЬНОЕ" },
        { "Miscellaneous", "Дополнительное" },
        { "Lua", "Скрипты" },
        { "Skin Changer", "Скин Ченджер" },
        { "Click to open live match radar", "Нажмите, чтобы открыть веб-радар" },
        { "Are you sure you want to exit the cheat?", "Вы точно хотите закрыть чит?" },
        { "Exit", "Выход" },
        { "No", "Нет" },
        { "MAIN", "ОСНОВНОЕ" },
        { "SURVIVOR", "ВЫЖИВШИЙ" },
        { "HUNTER", "ОХОТНИК" },
        { "WORLD", "МИР" },
        { "Lua scripts", "Lua скрипты" },
        { "Lua # ", "Lua # " },
        { "Everyone", "Все" },
        { "Suvivor", "Выживший" },
        { "Hunter", "Охотник" },
        { "Hold", "Удерживать" },
        { "Lock", "Фиксировать" },
        { "Aimbot", "Аимбот" },
        { "Help with cursor fine-tuning", "Помощь в прицеливании" },
        { "Auto Fire", "Авто Стрельба" },
        { "Predict", "Предсказывать" },
        { "FOV Radius", "FOV Радиус" },
        { "Target", "Цель" },
        { "Mode", "Режим" },
        { "Distance Mode", "Режим Дистанции" },
        { "Field Of View", "Угол обзора" },
        { "Sensitivity", "Чувствительность" },
        { "Smooth", "Плавность" },
        { "Predict Offset", "Прогнозируемое Смещение" },
        { "Prediction offset", "Прогнозируемое Смещение" },
        { "Lag Switch", "Фейк Лаги" },
        { "Block", "Блокировать Пакеты" },
        { "Incoming", "Входящие" },
        { "Outgoing", "Исходящие" },
        { "All", "Все" },
        { "Beep Sound", "Звуковой Сигнал" },
        { "Auto pallet drop", "Авто скидывание паллеты" },
        { "Rapid drop", "Скидывание телепортом" },
        { "Rapid mode", "Режим телепорта" },
        { "Legit", "Легитный" },
        { "Blatant", "Агрессивный" },
        { "Ignore status", "Игнорировать статус" },
        { "Activation key", "Кнопка активации" },
        { "Drop distance", "Дистанция скидывания" },
        { "Direction offset", "Смещение направления" },
        { "Remove baited check", "Убрать чек на провоцирование" },
        { "Auto skill", "Авто навык" },
        { "Distance", "Дистанция" },
        { "Cooldown", "Перезарядка" },
        { "Detail setup", "Доп. настройки" },
        { "Second press", "Второе нажатие" },
        { "Second press delay", "Задержка второго нажатия" },
        { "When facing angle", "При повороте лицом к тебе" },
        { "Angle value", "Угол поворота" },
        { "Hunter automations", "Автоматизация охотника" },
        { "Select Hunter", "Выбрать охотника" },
        { "Evil Reptilian", "Злая Рептилия" },
        { "Guard 26", "Страж 26" },
        { "Violinis", "Скрипач" },
        { "Axe Boy", "Мальчик с топором" },
        { "Wu Chang", "Ву Чанг" },
        { "Auto lizard jump", "Авто прыжок ящера" },
        { "Radius", "Радиус" },
        { "Predict position", "Предсказывать позицию" },
        { "Auto bomb", "Авто бомбы" },
        { "Drop offset", "Смещение скидывания" },
        { "Aim at second", "Наводка при второй бомбе" },
        { "Auto violinist", "Авто скрипач" },
        { "Threshold", "Погрешность" },
        { "Auto Robbie", "Авто Робби" },
        { "Hit Threshold", "Погрешность атаки" },
        { "Umbrella helper", "Помощь с зонтиком" },
        { "Teleport on distance", "Телепорт при дистанции" },
        { "Draw ESP", "Рисовать ESP" },
        { "DMA Background", "DMA Фон" },
        { "Entities Panel", "Панель сущностей" },
        { "Show only players", "Показывать только игроков" },
        { "Panel Corner", "Расположение панели" },
        { "Top Left", "Левый верхний" },
        { "Bottom Left", "Левый нижний" },
        { "Top Right", "Правый верхний" },
        { "Bottom Right", "Правый нижний" },
        { "Middle Left", "По центру слева" },
        { "Middle Right", "По центру справа" },
        { "Old FOV Method", "Старый FOV метод" },
        { "FOV Value", "Значение FOV" },
        { "No Fog", "Убрать туман" },
        { "Fog Value", "Значение тумана" },
        { "Widescreen 4:3", "Широкий экран" },
        { "Offscreen ESP", "ESP вне видимости" },
        { "Offset", "Смещение" },
        { "Triangle Size", "Размер треугольника" },
        { "Survivor", "Выживший" },
        { "Draw survivor", "Рисовать выживших" },
        { "Draw boxes", "Рисовать квадраты" },
        { "BOX TYPE", "ТИП КВАДРАТОВ" },
        { "Standart", "Стандарт" },
        { "Corner box", "Угловой" },
        { "Circle", "Круг" },
        { "Draw snap line", "Рисовать линию привязки" },
        { "SNAP LINE TYPE", "ТИП ЛИНИИ ПРИВЯЗКИ" },
        { "Upper", "Вверху" },
        { "Center", "По центру" },
        { "Bottom", "Снизу" },
        { "Max render distance", "Макс расстояние рендера" },
        { "Draw distance", "Рисовать дистанцию" },
        { "Draw objects", "Рисовать объекты" },
        { "Draw mirrored", "Рисовать зеркальных" },
        { "Lizard Helper", "Помощник Ящера" },
        { "Items", "Предметы" },
        { "Draw items", "Рисовать предметы" },
        { "ITEM BOX TYPE", "Тип квадратов для предметов" },
        { "Hunter", "Охотник" },
        { "Draw hunter", "Рисовать охотника" },
        { "Peeper ESP", "Пипер ESP" },
        { "Show while waiting", "Показывать в подборе" },
        { "Show skill indicator", "Показывать индикатор навыка" },
        { "Pallets", "Паллеты" },
        { "Draw pallets", "Рисовать паллеты" },
        { "Draw status", "Рисовать статус" },
        { "Ciphers", "Генераторы" },
        { "Draw ciphers", "Рисовать генераторы" },
        { "Show progress", "Показывать прогресс" },
        { "Cabinets", "Шкафы" },
        { "Draw cabinets", "Рисовать шкафы" },
        { "Gallows", "Стулья" },
        { "Draw gallows", "Рисовать стулья" },
        { "Dungeon", "Люк" },
        { "Draw dungeon", "Рисовать люк" },
        { "Draw chests", "Рисовать сундуки" },
        { "Chests", "Сундуки" },

        { "THEME", "ТЕМА" },
        { "Blue", "Синяя" },
        { "Purple", "Фиолетовая" },
        { "Custom", "Пользовательская" },
        { "CUSTOM", "ПОЛЬЗОВАТЕЛЬСКИЙ" },
        { "Custom colors", "Свои цвета" },
        { "Color 1", "Цвет 1" },
        { "Color 2", "Цвет 2" },
        { "Transparency", "Прозрачность" },
        { "Refresh", "Обновить" },
        { "Folder", "Папка" },
        { "Save colors to theme", "Сохранить цвета в тему" },
        { "Setup", "Установить" },
        { "Protect Screen", "Защитить экран" },
        { "Safe Mode", "Безопасный режим" },
        { "Watermark", "Водяной знак" },
        { "Active Binds", "Активные функции" },
        { "Menu Open Key", "Клавиша открытия меню" },
        { "Discord RPC", "Discord RPC" },
        { "Skateware Watermark", "Водяной знак Skateware" },
        { "Skateware Chat", "Чат Skateware" },
        { "Chat Transparency", "Прозрачность чата" },
        { "DPI SCALE", "МАСШТАБ DPI" },
        { "CONFIG", "КОНФИГУРАЦИЯ" },
        { "Alpha", "Альфа" },
        { "Beta", "Бета" },
        { "Gamma", "Гамма" },
        { "Delta", "Дельта" },
        { "Zeta", "Зета" },
        { "Load", "Загрузить" },
        { "Save", "Сохранить" },
        { "Open Folder", "Открыть папку" },
        { "Python", "Python" },
        { "Extend functionality now!", "Расширьте функциональность сейчас!" },
        { "Enable", "Включить" },
        { "Show nicknames", "Показать никнеймы" },
        { "Show skill", "Показать навык" },
        { "Show talents", "Показать таланты" },
        { "Show bots", "Показать ботов" },
        { "Python not initialised", "Python не запущен" },
        { "Install Python", "Установить Python" },

        { "SKIN CHANGER", "ИЗМЕНЕНИЕ СКИНОВ" },
        { "PREVIEW ACCESS", "ПРЕДПРОСМОТР" },
        { "Apply Skin", "Применить скин" },
        { "Restore Default", "Восстановить все" },
        { "You don't have access to Skin Changer!", "У вас нет доступа к изменению скинов!" },
        { "Select any skin", "Выбрать любой скин" },
        { "CHARACTER", "ПЕРСОНАЖ" },
        { "SKIN NAME", "ИМЯ СКИНА" },
        { "Skin Preview", "Предпросмотр скина" },
        { "To use Skin Changer, you need to purchase a subscription \nto the cheat supplement on the skateware.win website.", "Чтобы использовать изменение скинов, вам нужно приобрести подписку \nна дополнение к читу на сайте skateware.win." },
        { "Your task is to first select the Default skin of the desired character, \nthen select the desired skin in the Skin Changer settings and click Apply. \nYou don't need to do anything else with skins. \nIt is also forbidden to change the skin until the skinchanger restores the skins. \nOtherwise, you will not be allowed into the match.", "Вам нужно сначала выбрать стандартный скин нужного персонажа, \nзатем выбрать нужный скин в настройках изменителя скинов и нажать Применить. \nВам не нужно ничего больше делать с скинами. \nТакже запрещено менять скин, пока изменитель скинов не восстановит скины. \nИначе вас не допустят в матч." },
        
        { "None", "Не установлено"},
        { "Input the letter", "Выберите кнопку"},
        { "Always on", "Всегда включено"},
        { "Hold", "Удерживать"},
        { "Toggle", "Переключение"},
        { "Force off", "Отключение"},
        { "Configurate", "Настройка"},

        { "Version: ", "Версия: "},
        { "Author: ", "Автор: "},
        { "Stop##", "Отключить##" },
        { "Load##", "Включить##" },
        { "Create", "Создать" },
        { "File Name w/o .lua", "Имя файла без .lua" },
        { "Open skateware folder", "Открыть папку skateware" },
        { "Open resources marketplace", "Открыть магазин скриптов" },
        { "Open docs", "Открыть документацию" },
        { "Refresh cloud scripts", "Перезагрузить облачные скрипты" },

        { "ESP: ", "ESP: " },
        { "Auto pallet: ", "Авто паллета: " },
        { "Field Of View: ", "Поле видимости: " },
        { "Lizard jump: ", "Прыжок ящера: " },
        { "Lizard Helper: ", "Помощник ящера: " },
        { "Aimbot: ", "Аимбот: " },
        { "Auto skill: ", "Авто навык: " },
        { "Wu Chang Helper: ", "Помощник Ву Чанга: " },
        { "Lag Switch: ", "Фейк лаги: " },

    };
}

#endif // LOCALIZATION_RU_H
 